--liquibase formatted sql

--changeset mpianello:1
create table matches (
	year        integer primary key,
	day_of_year integer not null check (day_of_year between 1 and 366),
	id_equipo_1 integer,
	id_equipo_2 integer
);

--changeset mpianello:2
insert into matches (year, day_of_year) values (1930, 16);
insert into matches (year, day_of_year) values (1931, 13);
insert into matches (year, day_of_year) values (1932, 67);
insert into matches (year, day_of_year) values (1933, 227);
insert into matches (year, day_of_year) values (1934, 260);
insert into matches (year, day_of_year) values (1935, 92);
insert into matches (year, day_of_year) values (1936, 102);
insert into matches (year, day_of_year) values (1937, 199);
insert into matches (year, day_of_year) values (1938, 97);
insert into matches (year, day_of_year) values (1939, 96);
insert into matches (year, day_of_year) values (1940, 146);
insert into matches (year, day_of_year) values (1941, 59);
insert into matches (year, day_of_year) values (1942, 139);
insert into matches (year, day_of_year) values (1943, 145);
insert into matches (year, day_of_year) values (1944, 1);
insert into matches (year, day_of_year) values (1945, 350);
insert into matches (year, day_of_year) values (1946, 136);
insert into matches (year, day_of_year) values (1947, 118);
insert into matches (year, day_of_year) values (1948, 4);
insert into matches (year, day_of_year) values (1949, 76);
insert into matches (year, day_of_year) values (1950, 254);
insert into matches (year, day_of_year) values (1951, 309);
insert into matches (year, day_of_year) values (1952, 324);
insert into matches (year, day_of_year) values (1953, 155);
insert into matches (year, day_of_year) values (1954, 233);
insert into matches (year, day_of_year) values (1955, 18);
insert into matches (year, day_of_year) values (1956, 175);
insert into matches (year, day_of_year) values (1957, 62);
insert into matches (year, day_of_year) values (1958, 59);
insert into matches (year, day_of_year) values (1959, 214);
insert into matches (year, day_of_year) values (1960, 366);
insert into matches (year, day_of_year) values (1961, 104);
insert into matches (year, day_of_year) values (1962, 364);
insert into matches (year, day_of_year) values (1963, 106);
insert into matches (year, day_of_year) values (1964, 208);
insert into matches (year, day_of_year) values (1965, 219);
insert into matches (year, day_of_year) values (1966, 251);
insert into matches (year, day_of_year) values (1967, 286);
insert into matches (year, day_of_year) values (1968, 165);
insert into matches (year, day_of_year) values (1969, 222);
insert into matches (year, day_of_year) values (1970, 129);
insert into matches (year, day_of_year) values (1971, 34);
insert into matches (year, day_of_year) values (1972, 253);
insert into matches (year, day_of_year) values (1973, 358);
insert into matches (year, day_of_year) values (1974, 186);
insert into matches (year, day_of_year) values (1975, 1);
insert into matches (year, day_of_year) values (1976, 73);
insert into matches (year, day_of_year) values (1977, 298);
insert into matches (year, day_of_year) values (1978, 87);
insert into matches (year, day_of_year) values (1979, 230);
insert into matches (year, day_of_year) values (1980, 194);
insert into matches (year, day_of_year) values (1981, 233);
insert into matches (year, day_of_year) values (1982, 311);
insert into matches (year, day_of_year) values (1983, 162);
insert into matches (year, day_of_year) values (1984, 53);
insert into matches (year, day_of_year) values (1985, 203);
insert into matches (year, day_of_year) values (1986, 40);
insert into matches (year, day_of_year) values (1987, 94);
insert into matches (year, day_of_year) values (1988, 51);
insert into matches (year, day_of_year) values (1989, 45);
insert into matches (year, day_of_year) values (1990, 359);
insert into matches (year, day_of_year) values (1991, 254);
insert into matches (year, day_of_year) values (1992, 135);
insert into matches (year, day_of_year) values (1993, 226);
insert into matches (year, day_of_year) values (1994, 216);
insert into matches (year, day_of_year) values (1995, 104);
insert into matches (year, day_of_year) values (1996, 51);
insert into matches (year, day_of_year) values (1997, 12);
insert into matches (year, day_of_year) values (1998, 212);
insert into matches (year, day_of_year) values (1999, 327);
insert into matches (year, day_of_year) values (2000, 266);
insert into matches (year, day_of_year) values (2001, 193);
insert into matches (year, day_of_year) values (2002, 17);
insert into matches (year, day_of_year) values (2003, 365);
insert into matches (year, day_of_year) values (2004, 299);
insert into matches (year, day_of_year) values (2005, 81);
insert into matches (year, day_of_year) values (2006, 59);
insert into matches (year, day_of_year) values (2007, 262);
insert into matches (year, day_of_year) values (2008, 19);
insert into matches (year, day_of_year) values (2009, 111);
insert into matches (year, day_of_year) values (2010, 121);
insert into matches (year, day_of_year) values (2011, 103);
insert into matches (year, day_of_year) values (2012, 35);
insert into matches (year, day_of_year) values (2013, 169);
insert into matches (year, day_of_year) values (2014, 198);
insert into matches (year, day_of_year) values (2015, 49);
insert into matches (year, day_of_year) values (2016, 241);
insert into matches (year, day_of_year) values (2017, 210);
insert into matches (year, day_of_year) values (2018, 187);

--changeset grios:3
create table players (
	id        integer primary key,
	name      varchar2(100) not null unique
);
--changeset grios:4
insert into players (id,name) values (1,'aguilar,francisco');
insert into players (id,name) values (2,'alarcón,salomón');
insert into players (id,name) values (3,'álvarez,medellín felipe');
insert into players (id,name) values (4,'rios,gaston');
insert into players (id,name) values (5,'gastan,victor');
insert into players (id,name) values (6,'camarena,alonso');
insert into players (id,name) values (7,'morelos,óscar');
insert into players (id,name) values (8,'camargo,alonso');
insert into players (id,name) values (9,'gaspar,alonso');
insert into players (id,name) values (10,'camarillo,alonso');
insert into players (id,name) values (11,'camau,alonso');
insert into players (id,name) values (12,'camberos,óscar');
insert into players (id,name) values (13,'cambray,óscar');
insert into players (id,name) values (14,'camino,óscar');
insert into players (id,name) values (15,'campa,óscar');
insert into players (id,name) values (16,'campillo,óscar');
insert into players (id,name) values (17,'teutli,rodrigo');
insert into players (id,name) values (18,'texeda,rodrigo');
insert into players (id,name) values (19,'teyes,rodrigo');
insert into players (id,name) values (20,'teyo,rodrigo');
insert into players (id,name) values (21,'thelles,rodrigo');
insert into players (id,name) values (22,'thobar,rodrigo');
insert into players (id,name) values (23,'thorres,rodrigo');
insert into players (id,name) values (24,'thovar,rodrigo');
insert into players (id,name) values (25,'tierra,rodrigo');
insert into players (id,name) values (26,'tierrablanca,rodrigo');
insert into players (id,name) values (27,'campirano,óscar');
insert into players (id,name) values (28,'campos,javier');
insert into players (id,name) values (29,'camposano,javier');
insert into players (id,name) values (30,'campusano,javier');
insert into players (id,name) values (31,'cana,óscar');
insert into players (id,name) values (32,'canal,óscar');
insert into players (id,name) values (33,'gandara,gustavo');
insert into players (id,name) values (34,'gaona,gustavo');
insert into players (id,name) values (35,'garambuyo,gustavo');
insert into players (id,name) values (36,'garate,gustavo');
insert into players (id,name) values (37,'garavito,gustavo');
insert into players (id,name) values (38,'garay,gustavo');
insert into players (id,name) values (39,'acosta,rodrigo');
insert into players (id,name) values (40,'garcia,alberto');
insert into players (id,name) values (50,'gardea,alberto');
insert into players (id,name) values (51,'garduno,alberto');
insert into players (id,name) values (52,'garfias,alberto');
insert into players (id,name) values (53,'garia,alberto');
insert into players (id,name) values (54,'garibai,alberto');
insert into players (id,name) values (55,'garibaldo,alberto');
insert into players (id,name) values (56,'garibay,alberto');
insert into players (id,name) values (57,'pedrosa ,martin');
insert into players (id,name) values (58,'garivay,alberto');
insert into players (id,name) values (59,'garnica,alberto');
insert into players (id,name) values (60,'acosta,matias');
insert into players (id,name) values (61,'garrido,alberto');
insert into players (id,name) values (62,'garsa,alberto');
insert into players (id,name) values (63,'garsia,alberto');
insert into players (id,name) values (64,'garza,raúl');
insert into players (id,name) values (65,'acevedo,pablo');
insert into players (id,name) values (66,'teyo,maximo');
insert into players (id,name) values (67,'garzia,raúl');
insert into players (id,name) values (68,'gasca,raúl');
insert into players (id,name) values (69,'gascon,raúl');
insert into players (id,name) values (70,'gaspar,raúl');
insert into players (id,name) values (71,'gastan,raúl');
insert into players (id,name) values (72,'gatica,raúl');
insert into players (id,name) values (73,'álvarez, salvador');
insert into players (id,name) values (74,'gauna,alberto');
insert into players (id,name) values (75,'villalva,santiago');
insert into players (id,name) values (76,'villalvazo,salvador');
insert into players (id,name) values (77,'villamar,gabriel');
insert into players (id,name) values (78,'villami,gabriel');
insert into players (id,name) values (79,'villanueba,gabriel');
insert into players (id,name) values (80,'villapando,salvador');
insert into players (id,name) values (81,'moral,óscar');
insert into players (id,name) values (82,'morales,óscar');
insert into players (id,name) values (83,'morantes,óscar');
insert into players (id,name) values (84,'moras,óscar');
insert into players (id,name) values (85,'morelos,salvador');
insert into players (id,name) values (86,'moreno,óscar');
insert into players (id,name) values (87,'morentin,óscar');
insert into players (id,name) values (88,'patron,francisco');
insert into players (id,name) values (89,'paulin,lucas');
insert into players (id,name) values (90,'paura,lucas');
insert into players (id,name) values (91,'pavon,tomas');
insert into players (id,name) values (92,'paz,tomas        ');
insert into players (id,name) values (93,'alarcón,gerardo genaro');
insert into players (id,name) values (94,'pecina,tomas');
insert into players (id,name) values (95,'pedraza,tomas');
insert into players (id,name) values (96,'pedrosa,lucas');
insert into players (id,name) values (97,'morelos,tomas');
insert into players (id,name) values (98,'peeres,lucas');
insert into players (id,name) values (99,'aguilar,dorantes');
insert into players (id,name) values (100,'camarena,dorantes');


commit;