--liquibase formatted sql

--changeset mpianello:1
CREATE TABLE matches (
	year        INTEGER PRIMARY KEY,
	day_of_year INTEGER NOT NULL CHECK (day_of_year BETWEEN 1 AND 366),
	id_equipo_1 INTEGER,
	id_equipo_2 INTEGER
);

--changeset mpianello:2
INSERT INTO matches (year, day_of_year) VALUES (1930, 16);
INSERT INTO matches (year, day_of_year) VALUES (1931, 13);
INSERT INTO matches (year, day_of_year) VALUES (1932, 67);
INSERT INTO matches (year, day_of_year) VALUES (1933, 227);
INSERT INTO matches (year, day_of_year) VALUES (1934, 260);
INSERT INTO matches (year, day_of_year) VALUES (1935, 92);
INSERT INTO matches (year, day_of_year) VALUES (1936, 102);
INSERT INTO matches (year, day_of_year) VALUES (1937, 199);
INSERT INTO matches (year, day_of_year) VALUES (1938, 97);
INSERT INTO matches (year, day_of_year) VALUES (1939, 96);
INSERT INTO matches (year, day_of_year) VALUES (1940, 146);
INSERT INTO matches (year, day_of_year) VALUES (1941, 59);
INSERT INTO matches (year, day_of_year) VALUES (1942, 139);
INSERT INTO matches (year, day_of_year) VALUES (1943, 145);
INSERT INTO matches (year, day_of_year) VALUES (1944, 1);
INSERT INTO matches (year, day_of_year) VALUES (1945, 350);
INSERT INTO matches (year, day_of_year) VALUES (1946, 136);
INSERT INTO matches (year, day_of_year) VALUES (1947, 118);
INSERT INTO matches (year, day_of_year) VALUES (1948, 4);
INSERT INTO matches (year, day_of_year) VALUES (1949, 76);
INSERT INTO matches (year, day_of_year) VALUES (1950, 254);
INSERT INTO matches (year, day_of_year) VALUES (1951, 309);
INSERT INTO matches (year, day_of_year) VALUES (1952, 324);
INSERT INTO matches (year, day_of_year) VALUES (1953, 155);
INSERT INTO matches (year, day_of_year) VALUES (1954, 233);
INSERT INTO matches (year, day_of_year) VALUES (1955, 18);
INSERT INTO matches (year, day_of_year) VALUES (1956, 175);
INSERT INTO matches (year, day_of_year) VALUES (1957, 62);
INSERT INTO matches (year, day_of_year) VALUES (1958, 59);
INSERT INTO matches (year, day_of_year) VALUES (1959, 214);
INSERT INTO matches (year, day_of_year) VALUES (1960, 366);
INSERT INTO matches (year, day_of_year) VALUES (1961, 104);
INSERT INTO matches (year, day_of_year) VALUES (1962, 364);
INSERT INTO matches (year, day_of_year) VALUES (1963, 106);
INSERT INTO matches (year, day_of_year) VALUES (1964, 208);
INSERT INTO matches (year, day_of_year) VALUES (1965, 219);
INSERT INTO matches (year, day_of_year) VALUES (1966, 251);
INSERT INTO matches (year, day_of_year) VALUES (1967, 286);
INSERT INTO matches (year, day_of_year) VALUES (1968, 165);
INSERT INTO matches (year, day_of_year) VALUES (1969, 222);
INSERT INTO matches (year, day_of_year) VALUES (1970, 129);
INSERT INTO matches (year, day_of_year) VALUES (1971, 34);
INSERT INTO matches (year, day_of_year) VALUES (1972, 253);
INSERT INTO matches (year, day_of_year) VALUES (1973, 358);
INSERT INTO matches (year, day_of_year) VALUES (1974, 186);
INSERT INTO matches (year, day_of_year) VALUES (1975, 1);
INSERT INTO matches (year, day_of_year) VALUES (1976, 73);
INSERT INTO matches (year, day_of_year) VALUES (1977, 298);
INSERT INTO matches (year, day_of_year) VALUES (1978, 87);
INSERT INTO matches (year, day_of_year) VALUES (1979, 230);
INSERT INTO matches (year, day_of_year) VALUES (1980, 194);
INSERT INTO matches (year, day_of_year) VALUES (1981, 233);
INSERT INTO matches (year, day_of_year) VALUES (1982, 311);
INSERT INTO matches (year, day_of_year) VALUES (1983, 162);
INSERT INTO matches (year, day_of_year) VALUES (1984, 53);
INSERT INTO matches (year, day_of_year) VALUES (1985, 203);
INSERT INTO matches (year, day_of_year) VALUES (1986, 40);
INSERT INTO matches (year, day_of_year) VALUES (1987, 94);
INSERT INTO matches (year, day_of_year) VALUES (1988, 51);
INSERT INTO matches (year, day_of_year) VALUES (1989, 45);
INSERT INTO matches (year, day_of_year) VALUES (1990, 359);
INSERT INTO matches (year, day_of_year) VALUES (1991, 254);
INSERT INTO matches (year, day_of_year) VALUES (1992, 135);
INSERT INTO matches (year, day_of_year) VALUES (1993, 226);
INSERT INTO matches (year, day_of_year) VALUES (1994, 216);
INSERT INTO matches (year, day_of_year) VALUES (1995, 104);
INSERT INTO matches (year, day_of_year) VALUES (1996, 51);
INSERT INTO matches (year, day_of_year) VALUES (1997, 12);
INSERT INTO matches (year, day_of_year) VALUES (1998, 212);
INSERT INTO matches (year, day_of_year) VALUES (1999, 327);
INSERT INTO matches (year, day_of_year) VALUES (2000, 266);
INSERT INTO matches (year, day_of_year) VALUES (2001, 193);
INSERT INTO matches (year, day_of_year) VALUES (2002, 17);
INSERT INTO matches (year, day_of_year) VALUES (2003, 365);
INSERT INTO matches (year, day_of_year) VALUES (2004, 299);
INSERT INTO matches (year, day_of_year) VALUES (2005, 81);
INSERT INTO matches (year, day_of_year) VALUES (2006, 59);
INSERT INTO matches (year, day_of_year) VALUES (2007, 262);
INSERT INTO matches (year, day_of_year) VALUES (2008, 19);
INSERT INTO matches (year, day_of_year) VALUES (2009, 111);
INSERT INTO matches (year, day_of_year) VALUES (2010, 121);
INSERT INTO matches (year, day_of_year) VALUES (2011, 103);
INSERT INTO matches (year, day_of_year) VALUES (2012, 35);
INSERT INTO matches (year, day_of_year) VALUES (2013, 169);
INSERT INTO matches (year, day_of_year) VALUES (2014, 198);
INSERT INTO matches (year, day_of_year) VALUES (2015, 49);
INSERT INTO matches (year, day_of_year) VALUES (2016, 241);
INSERT INTO matches (year, day_of_year) VALUES (2017, 210);
INSERT INTO matches (year, day_of_year) VALUES (2018, 187);

--changeset grios:3
CREATE TABLE players (
	id   INTEGER PRIMARY KEY,
	name VARCHAR2(100) NOT NULL UNIQUE
);
--changeset grios:4
INSERT INTO players (id, name) VALUES (1, 'aguilar,francisco');
INSERT INTO players (id, name) VALUES (2, 'alarcón,salomón');
INSERT INTO players (id, name) VALUES (3, 'álvarez,medellín felipe');
INSERT INTO players (id, name) VALUES (4, 'rios,gaston');
INSERT INTO players (id, name) VALUES (5, 'gastan,victor');
INSERT INTO players (id, name) VALUES (6, 'camarena,alonso');
INSERT INTO players (id, name) VALUES (7, 'morelos,óscar');
INSERT INTO players (id, name) VALUES (8, 'camargo,alonso');
INSERT INTO players (id, name) VALUES (9, 'gaspar,alonso');
INSERT INTO players (id, name) VALUES (10, 'camarillo,alonso');
INSERT INTO players (id, name) VALUES (11, 'camau,alonso');
INSERT INTO players (id, name) VALUES (12, 'camberos,óscar');
INSERT INTO players (id, name) VALUES (13, 'cambray,óscar');
INSERT INTO players (id, name) VALUES (14, 'camino,óscar');
INSERT INTO players (id, name) VALUES (15, 'campa,óscar');
INSERT INTO players (id, name) VALUES (16, 'campillo,óscar');
INSERT INTO players (id, name) VALUES (17, 'teutli,rodrigo');
INSERT INTO players (id, name) VALUES (18, 'texeda,rodrigo');
INSERT INTO players (id, name) VALUES (19, 'teyes,rodrigo');
INSERT INTO players (id, name) VALUES (20, 'teyo,rodrigo');
INSERT INTO players (id, name) VALUES (21, 'thelles,rodrigo');
INSERT INTO players (id, name) VALUES (22, 'thobar,rodrigo');
INSERT INTO players (id, name) VALUES (23, 'thorres,rodrigo');
INSERT INTO players (id, name) VALUES (24, 'thovar,rodrigo');
INSERT INTO players (id, name) VALUES (25, 'tierra,rodrigo');
INSERT INTO players (id, name) VALUES (26, 'tierrablanca,rodrigo');
INSERT INTO players (id, name) VALUES (27, 'campirano,óscar');
INSERT INTO players (id, name) VALUES (28, 'campos,javier');
INSERT INTO players (id, name) VALUES (29, 'camposano,javier');
INSERT INTO players (id, name) VALUES (30, 'campusano,javier');
INSERT INTO players (id, name) VALUES (31, 'cana,óscar');
INSERT INTO players (id, name) VALUES (32, 'canal,óscar');
INSERT INTO players (id, name) VALUES (33, 'gandara,gustavo');
INSERT INTO players (id, name) VALUES (34, 'gaona,gustavo');
INSERT INTO players (id, name) VALUES (35, 'garambuyo,gustavo');
INSERT INTO players (id, name) VALUES (36, 'garate,gustavo');
INSERT INTO players (id, name) VALUES (37, 'garavito,gustavo');
INSERT INTO players (id, name) VALUES (38, 'garay,gustavo');
INSERT INTO players (id, name) VALUES (39, 'acosta,rodrigo');
INSERT INTO players (id, name) VALUES (40, 'garcia,alberto');
INSERT INTO players (id, name) VALUES (50, 'gardea,alberto');
INSERT INTO players (id, name) VALUES (51, 'garduno,alberto');
INSERT INTO players (id, name) VALUES (52, 'garfias,alberto');
INSERT INTO players (id, name) VALUES (53, 'garia,alberto');
INSERT INTO players (id, name) VALUES (54, 'garibai,alberto');
INSERT INTO players (id, name) VALUES (55, 'garibaldo,alberto');
INSERT INTO players (id, name) VALUES (56, 'garibay,alberto');
INSERT INTO players (id, name) VALUES (57, 'pedrosa ,martin');
INSERT INTO players (id, name) VALUES (58, 'garivay,alberto');
INSERT INTO players (id, name) VALUES (59, 'garnica,alberto');
INSERT INTO players (id, name) VALUES (60, 'acosta,matias');
INSERT INTO players (id, name) VALUES (61, 'garrido,alberto');
INSERT INTO players (id, name) VALUES (62, 'garsa,alberto');
INSERT INTO players (id, name) VALUES (63, 'garsia,alberto');
INSERT INTO players (id, name) VALUES (64, 'garza,raúl');
INSERT INTO players (id, name) VALUES (65, 'acevedo,pablo');
INSERT INTO players (id, name) VALUES (66, 'teyo,maximo');
INSERT INTO players (id, name) VALUES (67, 'garzia,raúl');
INSERT INTO players (id, name) VALUES (68, 'gasca,raúl');
INSERT INTO players (id, name) VALUES (69, 'gascon,raúl');
INSERT INTO players (id, name) VALUES (70, 'gaspar,raúl');
INSERT INTO players (id, name) VALUES (71, 'gastan,raúl');
INSERT INTO players (id, name) VALUES (72, 'gatica,raúl');
INSERT INTO players (id, name) VALUES (73, 'álvarez, salvador');
INSERT INTO players (id, name) VALUES (74, 'gauna,alberto');
INSERT INTO players (id, name) VALUES (75, 'villalva,santiago');
INSERT INTO players (id, name) VALUES (76, 'villalvazo,salvador');
INSERT INTO players (id, name) VALUES (77, 'villamar,gabriel');
INSERT INTO players (id, name) VALUES (78, 'villami,gabriel');
INSERT INTO players (id, name) VALUES (79, 'villanueba,gabriel');
INSERT INTO players (id, name) VALUES (80, 'villapando,salvador');
INSERT INTO players (id, name) VALUES (81, 'moral,óscar');
INSERT INTO players (id, name) VALUES (82, 'morales,óscar');
INSERT INTO players (id, name) VALUES (83, 'morantes,óscar');
INSERT INTO players (id, name) VALUES (84, 'moras,óscar');
INSERT INTO players (id, name) VALUES (85, 'morelos,salvador');
INSERT INTO players (id, name) VALUES (86, 'moreno,óscar');
INSERT INTO players (id, name) VALUES (87, 'morentin,óscar');
INSERT INTO players (id, name) VALUES (88, 'patron,francisco');
INSERT INTO players (id, name) VALUES (89, 'paulin,lucas');
INSERT INTO players (id, name) VALUES (90, 'paura,lucas');
INSERT INTO players (id, name) VALUES (91, 'pavon,tomas');
INSERT INTO players (id, name) VALUES (92, 'paz,tomas        ');
INSERT INTO players (id, name) VALUES (93, 'alarcón,gerardo genaro');
INSERT INTO players (id, name) VALUES (94, 'pecina,tomas');
INSERT INTO players (id, name) VALUES (95, 'pedraza,tomas');
INSERT INTO players (id, name) VALUES (96, 'pedrosa,lucas');
INSERT INTO players (id, name) VALUES (97, 'morelos,tomas');
INSERT INTO players (id, name) VALUES (98, 'peeres,lucas');
INSERT INTO players (id, name) VALUES (99, 'aguilar,dorantes');
INSERT INTO players (id, name) VALUES (100, 'camarena,dorantes');

commit;